services:
  api:
    env_file:
      - .env
    build: .
    container_name: intruder-api
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./analysis:/app/analysis
    depends_on:
      - srs

  srs:
    image: ossrs/srs:6
    container_name: srs
    ports:
      - "1935:1935" # RTMP ingest
      - "1985:1985" # SRS API
      - "8081:8080" # SRS HTTP (mapped to 8081)
    command: [ "./objs/srs", "-c", "conf/rtmp.conf" ]
